galaxy_info:
  role_name: avicontroller_vmware
  author: Gaurav Rastogi
  description: Ansible Role to setup Avi Controller on VMware
  company: Avi Networks
  license: Apache-2.0
  min_ansible_version: 2.2
  github_branch: master
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
  galaxy_tags:
    - avi
    - controller
    - avicontroller
    - avisdk
    - avinetworks
    - networks
    - load
    - balancer
    - sdk
    - lbaas
    - lb
    - virtualserver
    - cloud
    - loadbalancer
    - gslb
dependencies: []
